In [1]:
import numpy as np


In [4]:
a = [0,1,2,3,4,5,6,7,8,9,10]
print (a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [91]:
#question 2
a = np.ones (9).reshape (3,3)
print (a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [76]:
#question 3
c = np.arange (1,11,2)
print (c)


[1 3 5 7 9]


In [101]:
#question 4 - not quite right yet, need to look t replacing odds with -1
d = np.arange (1,11)
print (d)
d = (d),(-1)
print (d)

[ 1  2  3  4  5  6  7  8  9 10]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), -1)


In [108]:
d = np.arange(1, 10 , 1)
print(d)



[1 2 3 4 5 6 7 8 9]


In [83]:
#question 5
a = np.arange (8).reshape (2,4)
print (a)

[[0 1 2 3]
 [4 5 6 7]]


In [79]:
#question 6 (incorrect but leaving in for my referance)
e = np.arange (1,10).reshape (3,3)
f = np.arange (11,20).reshape (3,3)
print (e)
print (f)
g = np.dot (e,f)
print (g)
h = np.sum (g)
print (h)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
2079


In [50]:
#question 6
e = np.arange (1,10)
f = np.arange (11,20)
print (e)
print (f)
g = np.dot (e,f)
print (g)
h = np.sum (g)
print (h)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
735
735
